# Generated by Django 4.0.3 on 2022-04-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_managermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='num',
        ),
    ]
