# Generated by Django 4.0.3 on 2022-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_ordermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(default='+375 29', max_length=255),
        ),
    ]
