# Generated by Django 4.0.3 on 2022-03-25 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Production',
            new_name='ProductionModel',
        ),
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='SuppliersModel',
        ),
        migrations.RenameModel(
            old_name='Supply',
            new_name='SupplyModel',
        ),
        migrations.RenameModel(
            old_name='Wages',
            new_name='WagesModel',
        ),
    ]
