# Generated by Django 4.0.3 on 2022-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='data',
            field=models.DateField(default='2022-03-24'),
        ),
    ]
