# Generated by Django 4.0.3 on 2022-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_bidmodel_rename_schedule_schedulemodel_delete_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmodel',
            name='data',
            field=models.DateField(default='2022-04-12'),
        ),
    ]
