# Generated by Django 4.0.3 on 2022-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_alter_bidmodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmodel',
            name='data',
            field=models.DateField(default='2022-04-23'),
        ),
    ]
