version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      NAME: ameniel_db
      LOGIN: aleksey
      POSTGRES_PASSWORD: gt7tdi1sssd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080